# Generated by Django 3.0.3 on 2020-05-14 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('factura', '0005_auto_20200507_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='obsrvcn',
            field=models.CharField(default='Registro de consumo', max_length=150),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='prdo_cnsmo',
            field=models.CharField(default='202007', max_length=50),
        ),
        migrations.AlterField(
            model_name='pago',
            name='nmro_unco_idntfccn_usro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transformador',
            name='obsrvcn',
            field=models.CharField(default='Trasformador', max_length=150),
        ),
    ]
