# Generated by Django 3.0.3 on 2020-05-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0006_auto_20200514_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacion',
            name='estado',
            field=models.BooleanField(default='False'),
        ),
    ]
