# Generated by Django 3.0.3 on 2020-05-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0007_facturacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa',
            name='inco_vgca',
            field=models.DateField(auto_now_add=True),
        ),
    ]
