# Generated by Django 3.0.3 on 2020-05-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0008_auto_20200515_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa',
            name='inco_vgca',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
