# Generated by Django 3.0.3 on 2020-05-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0010_auto_20200515_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='nmro_trjt',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='tp_pgdo',
            field=models.CharField(default='Efectivo', max_length=20),
        ),
    ]
