# Generated by Django 3.0.3 on 2020-05-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0013_auto_20200517_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fcha_pgo',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
